#ifndef _MAP_UPDATE_KIND_
#define _MAP_UPDATE_KIND_

typedef enum {
	MAPUPDATE_NONE,
	MAPUPDATE_POINT_ADD,
	MAPUPDATE_POINT_DEL,
	MAPUPDATE_POINT_RESOURCE,
	MAPUPDATE_POINT_RESOURCE_OWNER_NAME,
	MAPUPDATE_POINT_RESOURCE_OWNER_TAG,
	MAPUPDATE_POINT_PLAYER_NAME,
	MAPUPDATE_POINT_PLAYER_TAG,
	MAPUPDATE_POINT_PLAYER_LEVEL,
	MAPUPDATE_POINT_PLAYER_CAPITALFLAG,
	MAPUPDATE_POINT_PLAYER_KTITLE,
	MAPUPDATE_POINT_PLAYER_WTITLE,
	MAPUPDATE_POINT_PLAYER_ADVANCE,
	MAPUPDATE_POINT_NPC_BLOOD,
	MAPUPDATE_LINE_ADD,
	MAPUPDATE_LINE_DEL,
	MAPUPDATE_LINE_OWNER_NAME,
	MAPUPDATE_LINE_OWNER_TAG,
	MAPUPDATE_LINE_BEGIN,
	MAPUPDATE_KINGDOM_FLAG,
	MAPUPDATE_KINGDOM_PERIOD,
	MAPUPDATE_KINGDOM_ALLIANCE,
	MAPUPDATE_MAX,
	MAPUPDATE_END,
	MAPUPDATE_ZONE_NONE,
	MAPUPDATE_KINGDOM,
	MAPUPDATE_KINGDOM_END,
	MAPUPDATE_KINGDOM_NONE,
	MAPUPDATE_POINT_YOLK_STATE,
	MAPUPDATE_POINT_YOLK_EMBLEM,
	MAPUPDATE_POINT_YOLK_LEADER_NAME,
	MAPUPDATE_POINT_YOLK_ALLIANCE_TAG,
	MAPUPDATE_POINT_YOLK_LEADER_POS,
	MAPUPDATE_POINT_YOLK_ALLIANCE_NAME,
	MAPUPDATE_POINT_YOLK_LEADER_HEAD,
	MAPUPDATE_POINT_YOLK_LEADER,
	MAPUPDATE_POINT_YOLK_OWNER,
	MAPUPDATE_POINT_YOLK_ALLIANCE,
	MAPUPDATE_POINT_YOLK_FLAG,
	MAPUPDATE_POINT_YOLK_ALLIANCE_KINGDOM,
	MAPUPDATE_KINGDOM_TIME,
	MAPUPDATE_KINGDOM_OWNERKINGDOMID,
	MAPUPDATE_POINT_PLAYER_ALLIANCE_KINGDOM,
	MAPUPDATE_POINT_YOLK_LEADER_HOME_KINGDOM,
	MAPUPDATE_LINE_EMOJI,
	MAPUPDATE_POINT_EMOJI,
	MAPUPDATE_POINT_NPC_TAG,
	MAPUPDATE_POINT_PLAYER_OUTWARD,
	MAPUPDATE_POINT_PLAYER_OUTWARD_LEVEL,
	MAPUPDATE_COUNT
} MAP_UPDATE_KIND;

const char *MapUpdateKindToString(MAP_UPDATE_KIND kind)
{
    switch (kind)
    {
        case MAPUPDATE_NONE: return "MAPUPDATE_NONE";
        case MAPUPDATE_POINT_ADD: return "MAPUPDATE_POINT_ADD";
        case MAPUPDATE_POINT_DEL: return "MAPUPDATE_POINT_DEL";
        case MAPUPDATE_POINT_RESOURCE: return "MAPUPDATE_POINT_RESOURCE";
        case MAPUPDATE_POINT_RESOURCE_OWNER_NAME: return "MAPUPDATE_POINT_RESOURCE_OWNER_NAME";
        case MAPUPDATE_POINT_RESOURCE_OWNER_TAG: return "MAPUPDATE_POINT_RESOURCE_OWNER_TAG";
        case MAPUPDATE_POINT_PLAYER_NAME: return "MAPUPDATE_POINT_PLAYER_NAME";
        case MAPUPDATE_POINT_PLAYER_TAG: return "MAPUPDATE_POINT_PLAYER_TAG";
        case MAPUPDATE_POINT_PLAYER_LEVEL: return "MAPUPDATE_POINT_PLAYER_LEVEL";
        case MAPUPDATE_POINT_PLAYER_CAPITALFLAG: return "MAPUPDATE_POINT_PLAYER_CAPITALFLAG";
        case MAPUPDATE_POINT_PLAYER_KTITLE: return "MAPUPDATE_POINT_PLAYER_KTITLE";
        case MAPUPDATE_POINT_PLAYER_WTITLE: return "MAPUPDATE_POINT_PLAYER_WTITLE";
        case MAPUPDATE_POINT_PLAYER_ADVANCE: return "MAPUPDATE_POINT_PLAYER_ADVANCE";
        case MAPUPDATE_POINT_NPC_BLOOD: return "MAPUPDATE_POINT_NPC_BLOOD";
        case MAPUPDATE_LINE_ADD: return "MAPUPDATE_LINE_ADD";
        case MAPUPDATE_LINE_DEL: return "MAPUPDATE_LINE_DEL";
        case MAPUPDATE_LINE_OWNER_NAME: return "MAPUPDATE_LINE_OWNER_NAME";
        case MAPUPDATE_LINE_OWNER_TAG: return "MAPUPDATE_LINE_OWNER_TAG";
        case MAPUPDATE_LINE_BEGIN: return "MAPUPDATE_LINE_BEGIN";
        case MAPUPDATE_KINGDOM_FLAG: return "MAPUPDATE_KINGDOM_FLAG";
        case MAPUPDATE_KINGDOM_PERIOD: return "MAPUPDATE_KINGDOM_PERIOD";
        case MAPUPDATE_KINGDOM_ALLIANCE: return "MAPUPDATE_KINGDOM_ALLIANCE";
        case MAPUPDATE_MAX: return "MAPUPDATE_MAX";
        case MAPUPDATE_END: return "MAPUPDATE_END";
        case MAPUPDATE_ZONE_NONE: return "MAPUPDATE_ZONE_NONE";
        case MAPUPDATE_KINGDOM: return "MAPUPDATE_KINGDOM";
        case MAPUPDATE_KINGDOM_END: return "MAPUPDATE_KINGDOM_END";
        case MAPUPDATE_KINGDOM_NONE: return "MAPUPDATE_KINGDOM_NONE";
        case MAPUPDATE_POINT_YOLK_STATE: return "MAPUPDATE_POINT_YOLK_STATE";
        case MAPUPDATE_POINT_YOLK_EMBLEM: return "MAPUPDATE_POINT_YOLK_EMBLEM";
        case MAPUPDATE_POINT_YOLK_LEADER_NAME: return "MAPUPDATE_POINT_YOLK_LEADER_NAME";
        case MAPUPDATE_POINT_YOLK_ALLIANCE_TAG: return "MAPUPDATE_POINT_YOLK_ALLIANCE_TAG";
        case MAPUPDATE_POINT_YOLK_LEADER_POS: return "MAPUPDATE_POINT_YOLK_LEADER_POS";
        case MAPUPDATE_POINT_YOLK_ALLIANCE_NAME: return "MAPUPDATE_POINT_YOLK_ALLIANCE_NAME";
        case MAPUPDATE_POINT_YOLK_LEADER_HEAD: return "MAPUPDATE_POINT_YOLK_LEADER_HEAD";
        case MAPUPDATE_POINT_YOLK_LEADER: return "MAPUPDATE_POINT_YOLK_LEADER";
        case MAPUPDATE_POINT_YOLK_OWNER: return "MAPUPDATE_POINT_YOLK_OWNER";
        case MAPUPDATE_POINT_YOLK_ALLIANCE: return "MAPUPDATE_POINT_YOLK_ALLIANCE";
        case MAPUPDATE_POINT_YOLK_FLAG: return "MAPUPDATE_POINT_YOLK_FLAG";
        case MAPUPDATE_POINT_YOLK_ALLIANCE_KINGDOM: return "MAPUPDATE_POINT_YOLK_ALLIANCE_KINGDOM";
        case MAPUPDATE_KINGDOM_TIME: return "MAPUPDATE_KINGDOM_TIME";
        case MAPUPDATE_KINGDOM_OWNERKINGDOMID: return "MAPUPDATE_KINGDOM_OWNERKINGDOMID";
        case MAPUPDATE_POINT_PLAYER_ALLIANCE_KINGDOM: return "MAPUPDATE_POINT_PLAYER_ALLIANCE_KINGDOM";
        case MAPUPDATE_POINT_YOLK_LEADER_HOME_KINGDOM: return "MAPUPDATE_POINT_YOLK_LEADER_HOME_KINGDOM";
        case MAPUPDATE_LINE_EMOJI: return "MAPUPDATE_LINE_EMOJI";
        case MAPUPDATE_POINT_EMOJI: return "MAPUPDATE_POINT_EMOJI";
        case MAPUPDATE_POINT_NPC_TAG: return "MAPUPDATE_POINT_NPC_TAG";
        case MAPUPDATE_POINT_PLAYER_OUTWARD: return "MAPUPDATE_POINT_PLAYER_OUTWARD";
        case MAPUPDATE_POINT_PLAYER_OUTWARD_LEVEL: return "MAPUPDATE_POINT_PLAYER_OUTWARD_LEVEL";
        case MAPUPDATE_COUNT: return "MAPUPDATE_COUNT";
        default: return "UNKNOWN_MAP_UPDATE_KIND";
    }
}

#endif