package com.igg.lordsm.panel

import com.igg.lordsm.panel.data.Account
import com.igg.lordsm.panel.feature.FeatureRegistry
import com.igg.lordsm.panel.feature.FieldType
import com.igg.lordsm.panel.feature.Risk
import java.io.File

/**
 * Renders an [Account] into the config format the C bot parses, enforcing
 * the safety mode on the way out.
 *
 * The mode clamp lives here rather than in the screens on purpose: this is
 * the single choke point where a UI toggle becomes an outbound packet, so
 * a screen that forgets to check cannot enable something the mode forbids.
 */
object ConfigWriter {

    fun write(target: File, account: Account): File {
        val values = HashMap<String, String>()
        for (spec in FeatureRegistry.all)
            values[spec.key] = account.values[spec.key] ?: spec.defaultValue

        values["server.addr"] = account.gatewayAddr
        values["server.port"] = account.gatewayPort
        values["account.igg_id"] = account.iggId
        values["account.device_uuid"] = account.deviceUuid
        values["account.access_key"] = account.accessKey
        values["admin.name"] = account.adminName.ifBlank { account.label }
        values["data.path"] = "./data/"

        FeatureRegistry.applyMode(values, account.ultraSafe)

        target.parentFile?.mkdirs()
        target.writeText(render(values))
        return target
    }

    private fun render(values: Map<String, String>): String = buildString {
        appendLine("# Generated by LordsBotPanel - do not edit by hand.")
        appendLine()
        appendLine("[server]")
        appendLine("addr = ${values["server.addr"]}")
        appendLine("port = ${values["server.port"]}")
        appendLine()
        appendLine("[account]")
        appendLine("igg_id = ${values["account.igg_id"]}")
        appendLine("device_uuid = ${values["account.device_uuid"]}")
        appendLine("access_key = ${values["account.access_key"]}")
        appendLine()
        appendLine("[command]")
        appendLine("prefix = ${values["command.prefix"]}")
        appendLine("input = ${values["command.input"]}")
        appendLine("output = ${values["command.output"]}")
        appendLine()
        appendLine("[admin]")
        appendLine("name = ${values["admin.name"]}")
        appendLine()

        val skipped = setOf("Identity")
        for (group in FeatureRegistry.groups) {
            if (group in skipped) continue
            appendLine("[$group]")
            for (spec in FeatureRegistry.forGroup(group)) {
                val v = values[spec.key] ?: continue
                appendLine("${spec.key.substringAfter('.')} = $v")
            }
            appendLine()
        }
    }

    /** How many non-risky toggles are actually on, for the dashboard. */
    fun enabledCount(account: Account): Int {
        val values = HashMap<String, String>()
        for (spec in FeatureRegistry.all)
            values[spec.key] = account.values[spec.key] ?: spec.defaultValue
        FeatureRegistry.applyMode(values, account.ultraSafe)
        return FeatureRegistry.all.count { spec ->
            spec.type == FieldType.TOGGLE && !spec.blocked &&
                values[spec.key] == "true" && spec.risk != Risk.RISKY
        }
    }
}
