package com.igg.lordsm.panel

import com.igg.lordsm.panel.data.Account
import com.igg.lordsm.panel.feature.FeatureRegistry
import com.igg.lordsm.panel.feature.FieldType
import com.igg.lordsm.panel.feature.Risk
import java.io.File

/**
 * Renders an [Account] into the config format the C bot parses, enforcing
 * the safety mode on the way out.
 *
 * The mode clamp lives here rather than in the screens on purpose: this is
 * the single choke point where a UI toggle becomes an outbound packet, so
 * a screen that forgets to check cannot enable something the mode forbids.
 */
object ConfigWriter {

    fun write(target: File, account: Account): File {
        val values = HashMap<String, String>()
        for (spec in FeatureRegistry.all)
            values[spec.key] = account.values[spec.key] ?: spec.defaultValue

        values["server.addr"] = account.gatewayAddr
        values["server.port"] = account.gatewayPort
        values["account.igg_id"] = account.iggId
        values["account.device_uuid"] = account.deviceUuid
        values["account.access_key"] = account.accessKey
        values["admin.name"] = account.adminName.ifBlank { account.label }
        values["data.path"] = "./data/"

        FeatureRegistry.applyMode(values, account.ultraSafe)

        target.parentFile?.mkdirs()
        target.writeText(render(values))
        return target
    }

    /**
     * Flat "full.key = value" lines, and nothing else.
     *
     * The engine's LoadConfig is literally
     *     sscanf(line, " %63[^=]= %511[^\n]", key, value)
     * with no notion of sections: a "[server]" header has no '=' and is
     * dropped, and an earlier version of this file emitted sections plus
     * prefix-stripped keys ("addr"), which the parser therefore never
     * recognised - every setting would have silently stayed at its
     * default. Do not add section headers here.
     */
    private fun render(values: Map<String, String>): String = buildString {
        appendLine("# Generated by LordsBotPanel - do not edit by hand.")
        appendLine("# Flat key = value: the engine's parser has no sections.")
        appendLine()
        for (spec in FeatureRegistry.all) {
            val key = spec.key
            val v = values[key] ?: continue
            appendLine("$key = $v")
        }
        // Identity keys that are not part of the registry table.
        for (k in EXTRA_KEYS) {
            val v = values[k] ?: continue
            appendLine("$k = $v")
        }
    }

    private val EXTRA_KEYS = listOf(
        "server.addr", "server.port", "account.igg_id", "account.device_uuid",
        "account.access_key", "admin.name", "data.path",
        "client.version_major", "client.version_minor", "client.version_patch",
        "client.language_code",
    )

    /** How many non-risky toggles are actually on, for the dashboard. */
    fun enabledCount(account: Account): Int {
        val values = HashMap<String, String>()
        for (spec in FeatureRegistry.all)
            values[spec.key] = account.values[spec.key] ?: spec.defaultValue
        FeatureRegistry.applyMode(values, account.ultraSafe)
        return FeatureRegistry.all.count { spec ->
            spec.type == FieldType.TOGGLE && !spec.blocked &&
                values[spec.key] == "true" && spec.risk != Risk.RISKY
        }
    }
}
